export const FALLBACK_DOCTORS = [
  {
    id: 'dr-aljazi-al-baqmi',
    slug: 'dr-aljazi-al-baqmi',
    name: { en: 'Dr. Aljazi Al-Baqmi', ar: 'د. الجازي البقمي' },
    specialty: {
      en: 'Dentist, 2 years of experience',
      ar: 'طبيبة أسنان، خبرة سنتان',
    },
    category: 'dentistry',
    categoryId: 'dentistry',
    imageKey: 'dr_aljazi',
    order: 1,
    published: true,
    featured: true,
  },
  {
    id: 'dr-hany-mostafa',
    slug: 'dr-hany-mostafa',
    name: { en: 'Dr. Hany Mostafa', ar: 'د. هاني مصطفى' },
    specialty: {
      en: 'General Practitioner, 10 years of experience',
      ar: 'طبيب عام، خبرة 10 سنوات',
    },
    category: 'generalMedicine',
    categoryId: 'general-medicine',
    imageKey: 'dr_hany',
    order: 2,
    published: true,
    featured: true,
  },
  {
    id: 'dr-thanaa-shehab',
    slug: 'dr-thanaa-shehab',
    name: { en: 'Dr. Thanaa Shehab Al-Din', ar: 'د. ثناء شهاب الدين' },
    specialty: {
      en: 'Obstetrics & Gynecology Specialist, 15 years of experience',
      ar: 'أخصائية توليد وأمراض نساء، خبرة 15 سنة',
    },
    category: 'generalMedicine',
    categoryId: 'obg',
    imageKey: 'dr_tanaa',
    order: 3,
    published: true,
    featured: true,
  },
  {
    id: 'dr-asmaa-shawqi',
    slug: 'dr-asmaa-shawqi',
    name: { en: 'Dr. Asmaa Shawqi', ar: 'د. أسماء شوقي' },
    specialty: {
      en: 'Family Medicine Specialist, 10 years of experience',
      ar: 'أخصائية طب الأسرة، خبرة 10 سنوات',
    },
    category: 'generalMedicine',
    categoryId: 'family-medicine',
    imageKey: 'dr_asma',
    order: 4,
    published: true,
    featured: true,
  },
  {
    id: 'dr-haifa-ali-khalid',
    slug: 'dr-haifa-ali-khalid',
    name: { en: 'Dr. Haifa Ali Khalid', ar: 'د. هيفاء علي خالد' },
    specialty: {
      en: 'Pediatrician, 30 years of experience',
      ar: 'طبيبة أطفال، خبرة 30 سنة',
    },
    category: 'paediatrics',
    categoryId: 'pediatrics',
    imageKey: 'dr_haifa',
    order: 5,
    published: true,
    featured: false,
  },
  {
    id: 'dr-waad-al-sayed',
    slug: 'dr-waad-al-sayed',
    name: { en: 'Dr. Waad Al-Sayed', ar: 'د. وعد السيد' },
    specialty: {
      en: 'Dentist, 5 years of experience',
      ar: 'طبيبة أسنان، خبرة 5 سنوات',
    },
    category: 'dentistry',
    categoryId: 'dentistry',
    imageKey: 'dr_waad',
    order: 6,
    published: true,
    featured: false,
  },
];

export const FALLBACK_SERVICES = [
  {
    id: 'general-medicine',
    slug: 'general-medicine',
    title: { en: 'General Medicine', ar: 'الطب العام' },
    description: {
      en: 'Feeling unwell or just need a routine check-up? Our doctors are here to listen, guide, and help you stay healthy — one visit at a time.',
      ar: 'تشعر بالتوعك أو تحتاج فقط لفحص روتيني؟ أطباؤنا هنا للاستماع والإرشاد ومساعدتك على البقاء بصحة جيدة - زيارة واحدة في كل مرة.',
    },
    iconKey: 'generalMedicine',
    categoryId: 'primary-care',
    order: 1,
    status: 'active',
    published: true,
  },
  {
    id: 'family-medicine',
    slug: 'family-medicine',
    title: { en: 'Family Medicine', ar: 'طب العائلة' },
    description: {
      en: 'Your trusted family doctor — from kids to grandparents. Our family doctors take the time to listen, and care — just like someone who\'s known you for years.',
      ar: 'طبيب عائلتك الموثوق - من الأطفال إلى الأجداد. يأخذ أطباء العائلة لدينا الوقت الكافي للاستماع والإرشاد والرعاية.',
    },
    iconKey: 'familyMedicine',
    categoryId: 'primary-care',
    order: 2,
    status: 'active',
    published: true,
  },
  {
    id: 'internal-medicine',
    slug: 'internal-medicine',
    title: { en: 'Internal Medicine', ar: 'الطب الباطني' },
    description: {
      en: 'Managing diabetes, hypertension, or other long-term conditions? We\'ll work with you closely, explain every step, and ensure you\'re never alone in your care journey.',
      ar: 'تدير مرض السكري أو ارتفاع ضغط الدم أو حالات طويلة الأمد أخرى؟ سنعمل معك عن كثب ونشرح كل خطوة.',
    },
    iconKey: 'internalMedicine',
    categoryId: 'primary-care',
    order: 3,
    status: 'active',
    published: true,
  },
  {
    id: 'obg',
    slug: 'obg',
    title: { en: 'Obstetrics & Gynecology (OBG)', ar: 'التوليد وأمراض النساء' },
    description: {
      en: 'From pregnancy care to women\'s wellness, our OBG specialists offer trusted, private, and supportive care — every step of the way.',
      ar: 'من رعاية الحمل إلى صحة المرأة، يقدم أخصائيو التوليد وأمراض النساء لدينا رعاية موثوقة وخاصة وداعمة.',
    },
    iconKey: 'obg',
    categoryId: 'womens-health',
    order: 4,
    status: 'active',
    published: true,
  },
  {
    id: 'orthopedics',
    slug: 'orthopedics',
    title: { en: 'Orthopedics', ar: 'أورثو' },
    description: {
      en: 'From joint pain to injuries, our Orthopedics team is only a call away — ready to support you through recovery always with care.',
      ar: 'من آلام المفاصل إلى الإصابات، فريق جراحة العظام لدينا على بُعد مكالمة هاتفية فقط.',
    },
    iconKey: 'ortho',
    categoryId: 'orthopedics',
    order: 5,
    status: 'active',
    published: true,
  },
  {
    id: 'dentistry',
    slug: 'dentistry',
    title: { en: 'Dentistry & Orthodontics', ar: 'طب الأسنان وتقويم الأسنان' },
    description: {
      en: 'Healthy smiles start here. From cleanings to braces and smile correction, our dental team combines expertise and precision in every visit.',
      ar: 'الابتسامات الصحية تبدأ هنا. من الفحوصات الروتينية والتنظيف إلى التقويم وتصحيح الابتسامة.',
    },
    iconKey: 'generalDentistry',
    categoryId: 'dental',
    order: 6,
    status: 'active',
    published: true,
  },
  {
    id: 'laboratory',
    slug: 'laboratory',
    title: { en: 'Laboratory', ar: 'معمل' },
    description: {
      en: 'When it comes to your health, trust matters. Our laboratory delivers accurate results with care, honesty, and attention.',
      ar: 'عندما يتعلق الأمر بصحتك، فإن الثقة أمر بالغ الأهمية. يقدم مختبرنا نتائج دقيقة بكل عناية وصدق.',
    },
    iconKey: 'laboratory',
    categoryId: 'diagnostics',
    order: 7,
    status: 'active',
    published: true,
  },
  {
    id: 'pediatrics',
    slug: 'pediatrics',
    title: { en: 'Pediatrics', ar: 'طب الأطفال' },
    description: {
      en: 'Family-centered care supporting the growth and wellness of children.',
      ar: 'قلق بشأن صحة أو نمو طفلك؟ يعامل أطباء الأطفال لدينا أطفالك الصغار برعاية لطيفة وصبر.',
    },
    iconKey: 'pediatrics',
    categoryId: 'pediatrics',
    order: 8,
    status: 'active',
    published: true,
  },
];
